const PORTFOLIO_CONTENT = {
  about: [
    "----------------------------------------",
    "  WILL HUANG — CYBERSECURITY STUDENT",
    "----------------------------------------",
    "Location: Cambridge, ON",
    "",
    "Computer Science student specializing in cybersecurity, currently",
    "pursuing a BSc in Computer Science at Wilfrid Laurier University",
    "(expected Aug 2027). Previously completed a BSc in Mathematics with",
    "a Minor in Computer Science & Statistics at the University of",
    "Toronto Mississauga (2020-2023).",
    "",
    "Focused on network security, threat detection, and building",
    "hands-on security tools -- from AI-assisted SOC log analysis to",
    "CTF exploitation. Comfortable across Python, C/C++, Docker, and",
    "Linux, with growing experience applying LLMs to security automation."
  ],
  education: [
    "----------------------------------------",
    "  EDUCATION",
    "----------------------------------------",
    "Wilfrid Laurier University -- Waterloo, ON",
    "  BSc in Computer Science (Expected Aug 2027)",
    "",
    "University of Toronto Mississauga -- Mississauga, ON",
    "  BSc in Mathematics, Minor in Computer Science & Statistics",
    "  (Sept 2020 - Apr 2023)"
  ],
  skills: [
    "----------------------------------------",
    "  SKILLS",
    "----------------------------------------",
    "Languages   : Python, C, C++, Java, JavaScript, HTML, CSS, Swift, R, SQL",
    "Frameworks  : PyTorch, TensorFlow, Pandas, Node.js, Express.js, React, Bootstrap",
    "Tools       : Git, Docker, MongoDB, Linux/Unix, LLM APIs, Microsoft Office",
    "",
    "type 'skills --verbose' for a categorized breakdown"
  ],
  "skills --verbose": [
    "----------------------------------------",
    "  SKILLS (detailed)",
    "----------------------------------------",
    "[ Security ]      Threat detection, log analysis, CTF/pentesting,",
    "                  ethical hacking workflows, network security",
    "[ Languages ]     Python, C, C++, Java, JavaScript, Swift, R, SQL",
    "[ Web ]           HTML, CSS, Node.js, Express.js, React, Bootstrap",
    "[ ML/AI ]         PyTorch, TensorFlow, LLM API integration",
    "[ Infra ]         Docker, Git, MongoDB, Linux/Unix"
  ],
  experience: [
    "----------------------------------------",
    "  EXPERIENCE",
    "----------------------------------------",
    "Michael Hill Fine Jeweller -- Sales Professional & Key Holder",
    "  May 2023 - Present",
    "  > Delivered personalized in-store and virtual consultations.",
    "  > Exceeded weekly sales targets and corporate KPIs by 20%,",
    "    ranking top 10% regionally.",
    "  > Managed opening/closing, staff supervision, and security",
    "    protocols as key holder.",
    "",
    "Pandora -- Sales Representative",
    "  Nov 2022 - May 2023",
    "  > Assisted customers with luxury product selection and processed",
    "    multi-method financial transactions securely.",
    "",
    "Osiris Vertical Farm -- Data Analyst",
    "  Apr 2022 - Apr 2023",
    "  > Optimized plant health by analyzing environmental and growth",
    "    data using Python, Pandas, and R.",
    "  > Applied predictive modelling and regression analysis to",
    "    forecast growth cycles."
  ],
  projects: [
    "----------------------------------------",
    "  PROJECTS",
    "----------------------------------------",
    "[1] Mini-Agentic SOC Log Parser (May 2026)",
    "    Containerized Python + Docker AI threat-detection agent using",
    "    the Google Gemini API to identify SQL injection and",
    "    brute-force SSH attacks from live logs in real time. Built a",
    "    structured JSON threat-classification pipeline to parse",
    "    attacker IPs and trigger simulated iptables blocking rules",
    "    with zero manual input.",
    "",
    "[2] Keylogger (Dec 2025)",
    "    Cross-platform Python application using pynput to capture",
    "    keyboard input and serialize it to JSON. Implemented",
    "    multi-threaded data handling via threading.Timer to",
    "    periodically POST collected data to a remote server.",
    "",
    "[3] Capture The Flag (Mar 2024)",
    "    Secured exploit flags via reverse engineering, active",
    "    penetration testing, and ethical hacking workflows.",
    "    Diagnosed packet data and system anomalies to isolate attack",
    "    signatures using hands-on log analysis tools.",
    "",
    "type 'project 1', 'project 2', or 'project 3' for a focused view"
  ],
  "project 1": [
    "----------------------------------------",
    "  PROJECT: Mini-Agentic SOC Log Parser",
    "----------------------------------------",
    "Date   : May 2026",
    "Stack  : Python, Docker, Google Gemini API",
    "",
    "Containerized AI threat-detection agent that identifies SQL",
    "injection and brute-force SSH attacks from live logs in real",
    "time. Automates defensive responses via a structured JSON",
    "threat-classification pipeline that parses attacker IPs and",
    "triggers simulated iptables blocking rules -- zero manual input."
  ],
  "project 2": [
    "----------------------------------------",
    "  PROJECT: Keylogger",
    "----------------------------------------",
    "Date   : Dec 2025",
    "Stack  : Python, pynput, threading",
    "",
    "Cross-platform application capturing keyboard input and",
    "serializing it to JSON, with multi-threaded handling via",
    "threading.Timer to periodically transmit data to a remote",
    "server via HTTP POST."
  ],
  "project 3": [
    "----------------------------------------",
    "  PROJECT: Capture The Flag",
    "----------------------------------------",
    "Date   : Mar 2024",
    "Stack  : Reverse engineering, pentesting tools",
    "",
    "Secured exploit flags via reverse engineering, active",
    "penetration testing, and ethical hacking workflows. Diagnosed",
    "network packet data and system anomalies to isolate attack",
    "signatures."
  ],
  certifications: [
    "----------------------------------------",
    "  CERTIFICATIONS",
    "----------------------------------------",
    "[x] Microsoft -- Intro to Microsoft Defender XDR Threat Protection",
    "[x] Google Cybersecurity Professional Certificate",
    "    -- Network Security, Security Risks & Foundations",
    "[x] Deep Learning & AI -- TensorFlow Skill Path, AI A-Z",
    "[x] Cybersecurity & Ethical Hacking -- Complete Cyber Security",
    "    Course, Learn Ethical Hacking",
    "[x] Software Development -- SQL Bootcamp, Beginning C++,",
    "    Learn React, Intro to Swift"
  ],
  contact: [
    "----------------------------------------",
    "  CONTACT",
    "----------------------------------------",
    "email    : osha09@pm.me",
    "phone    : 647-700-8630",
    "location : Cambridge, ON",
    "linkedin : see resume / ask directly",
    "",
    "type 'sudo hire will' if you're a recruiter ;)"
  ]
};
